[package]
name = "vlen-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
postcard = { version = "1.1", features = ["use-std"] }
serde_json = "1.0"
vlen = { path = "..", features = ["alloc", "serde"] }

[features]
default = ["simd"]
simd = ["vlen/simd"]

[[bin]]
name = "decode_arbitrary"
path = "fuzz_targets/decode_arbitrary.rs"
test = false
doc = false
bench = false

[[bin]]
name = "serde_arbitrary"
path = "fuzz_targets/serde_arbitrary.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
